### ISSUE TITLE
Permission/Websocket - Not able to log output to console

### ISSUE THREAD

**Issue by Mkohm** [athombv/com.athom.homeyscript#24]
Hi! 

I am not able to log anything to the console. Error messages are logged, but console.log() or log() does not seem to work. Looks like there is some problems related to permissions/web-socket as I receive a 403 followed by a lot of web socket errors. Anyone knows what is up? 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16581038/103802180-0adfa700-504f-11eb-9383-653f2ca979f0.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/16581038/103802432-6873f380-504f-11eb-9855-400d352f23dc.png">

**Comment by WeeJeWel** [comment]
We had [some issues on Homey Connect](https://status.homey.app/incidents/n7hlc2pq6gnv). Please try again :)
