### ISSUE TITLE
Is it possible to disable SSL verification in scripts?

### ISSUE THREAD

**Issue by alechenne** [athombv/com.athom.homeyscript#28]
Hello,

First of all, please let me congratulate for Homeyscript, it's simply clever and solve a lot of thing. 

I've some Tesla Powerwall and recently Tesla update their firmware to do a strong authentification. I solved the issue with Postman:

```
var myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");
var raw = JSON.stringify({"username":"customer","password":"XXXXXX","email":"XXXXXXXX","force_sm_off":false});

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: raw,
  redirect: 'follow'
};

fetch("https://192.168.1.XXX/api/login/Basic", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

and when I want to implement this in Homeyscript:

```
    try
    {
        response = await fetch("https://192.168.1.XXX/api/login/Basic",{
            "method": "POST",
            "headers": {
                "user-agent": "Homeyscript",
                "accept": "*/*",
                "accept-encoding": "gzip, deflate, br",
                "connection": "keep-alive",
                "content-type": "application/json"
            },
            "body": {
                "username": "customer",
                "password": "XXXXXX",
                "email": "XXXXXXXX",
                "force_sm_off": false
            },
            "insecureHTTPParser": false,
            "redirect": "follow"
        });
    }
    catch (err) {console.log(err);return false;}
```

I got the following error:

```
> FetchError: request to https://192.168.1.XXX/api/login/Basic failed, reason: unable to verify the first certificate
>     at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1461:11)
>     at ClientRequest.emit (events.js:311:20)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:311:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   message: 'request to https://192.168.1.108/api/login/Basic failed, reason: unable to verify the first certificate',
>   type: 'system',
>   errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
>   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```

FYI, in Postman, SSL verification is disabled.

Is the option "insecureHTTPParser" from nodde-fetch supported? If not, do you have any idea how to solve this issue?

Thanks in advance.

Kind regards

NB. I did a mistake with insecureHTTPParser , it has been set to true. But, setting to true don't change the result, I got always the smae error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by jeroenwienk** [comment]
Does this work?
```javascript
response = await fetch("https://192.168.1.XXX/api/login/Basic",{
  "method": "POST",
  "headers": {
    "user-agent": "Homeyscript",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-type": "application/json"
  },
  "body": {
    "username": "customer",
    "password": "XXXXXX",
    "email": "XXXXXXXX",
    "force_sm_off": false
  },
  "insecureHTTPParser": false,
  "redirect": "follow",
  agent: {
    rejectUnauthorized: false
  }
});
```

**Comment by alechenne** [comment]
> Does this work?
> 
> ```js
> response = await fetch("https://192.168.1.XXX/api/login/Basic",{
>   "method": "POST",
>   "headers": {
>     "user-agent": "Homeyscript",
>     "accept": "*/*",
>     "accept-encoding": "gzip, deflate, br",
>     "connection": "keep-alive",
>     "content-type": "application/json"
>   },
>   "body": {
>     "username": "customer",
>     "password": "XXXXXX",
>     "email": "XXXXXXXX",
>     "force_sm_off": false
>   },
>   "insecureHTTPParser": false,
>   "redirect": "follow",
>   agent: {
>     rejectUnauthorized: false
>   }
> });
> ```

Unfortunatly no. The error is the following:

TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object
    at new ClientRequest (_http_client.js:133:11)
    at request (https.js:314:10)
    at /node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/node_modules/node-fetch/lib/index.js:1407:9)
    at readPowerwall.js:16:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by jeroenwienk** [comment]
https://github.com/node-fetch/node-fetch/pull/921 seems they had it on a previous version but removed it. I don't mind providing https and http modules to HomeyScript so you can customize the agent. @WeeJeWel do you mind if we supply those modules to HomeyScript? I exect more local API's might have this problem with self-signed certificates.

**Comment by alechenne** [comment]
> [node-fetch/node-fetch#921](https://github.com/node-fetch/node-fetch/pull/921) seems they had it on a previous version but removed it. I don't mind providing https and http modules to HomeyScript so you can customize the agent. @WeeJeWel do you mind if we provide those modules to HomeyScript? I expect more local API's might have this problem with self-signed certificates.

Thanks for your feedback and for asking the possibility to modify.

**Comment by WeeJeWel** [comment]
Yeah no problem!

**Comment by jeroenwienk** [comment]
@alechenne If you install the latest version you should be able to override the agent.

```javascript
const httpsAgent = new https.Agent({
  rejectUnauthorized: false
});

const options = {
  agent: httpsAgent 
};

await fetch(url, options);
```

**Comment by alechenne** [comment]
> @alechenne If you install the latest version you should be able to override the agent.
> 
> ```js
> const httpsAgent = new https.Agent({
>   rejectUnauthorized: false
> });
> 
> const options = {
>   agent: httpsAgent 
> };
> 
> await fetch(url, options);
> ```

Great job. It works perfectly. Many thanks. Here after a piece of Homeyscript code and the result:

```
// -------- o - Configure these parameters -------- o -------- o 
let authorize_url ='https://192.168.1.xxx/api/login/Basic'
const username ='customer'
const email ='xxxx@xxxx.com'
const password ='xxxx'
const debug =true
// -------- o - Configure these parameters -------- o -------- o 

const reqHeaders = {
    "Content-Type":"application/json"
};

const httpsAgent = new https.Agent({
    keepAlive: true,
    rejectUnauthorized: false
});

const reqBody = JSON.stringify({
    "username":username,
    "password":password,
    "email":email,
    "force_sm_off":false
});

const reqOptions = {
    method: "POST",
    headers: reqHeaders,
    body: reqBody,
    agent: httpsAgent,
};

let response
try
{
     response =await fetch(authorize_url, reqOptions);
}
catch (err) {console.log(err);return false;}

if (debug) console.log('Response =',response.status,response.statusText);
if (! response.ok) throw Error('Invalid response');

let body =JSON.parse(await response.text());
if (debug) console.log('Body = \n',body);
let token =body.token;
console.log('Token = \n',token);
```

The result (console)

```
Response = 200 OK
Body = 
 {
  email: 'xxxx@xxxx.com',
  firstname: 'Tesla',
  lastname: 'Energy',
  roles: [ 'Home_Owner' ],
  token: 'VZtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==',
  provider: 'Basic',
  loginTime: '2021-02-22T18:07:34.978735808+01:00'
}
Token = 
 VZtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==

———————————————————
✅ Script Success

```

I'll now implement the complet process in order to retrieve the cookie that I've to used then with GET request.
