### ISSUE TITLE
version 3.2.3 should have an option to change fetch-agent

### ISSUE THREAD

**Issue by tboudri** [athombv/com.athom.homeyscript#34]
Version 3.2.3 should have an option to change the fetch-agent. 
Since have memory related issues with the current implementation of the node-fetch, i would like to use this option. But how do you use this option? I can't find anything related to this

**Comment by jeroenwienk** [comment]
You can see an example here https://github.com/athombv/com.athom.homeyscript/issues/28#issuecomment-783459556

**Comment by tboudri** [comment]
Thanks, i found it
