### ISSUE TITLE
Console output is displayed twice when HomeyScript is accessed by https

### ISSUE THREAD

**Issue by bm480** [athombv/com.athom.homeyscript#4]
Excerpt from the forum:
If you login through http:// instead of https:// the doubles will be gone probably :)

That does indeed seem to work, although I don't like the idea of having an insecure connection to my home network. Is it possible to implement the fix for https: also?

**Comment by bvdbos** [comment]
works for me now...

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
